export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const ADD_USERS_REQUEST = "ADD_USERS_REQUEST";
export const ADD_USERS_SUCCESS = "ADD_USERS_SUCCESS";
export const ADD_USERS_FAILURE = "ADD_USERS_FAILURE";

export const LOGIN_USERS_SUCCESS = "LOGIN_USERS_SUCCESS";
export const LOGOUT_USERS_SUCCESS = "LOGOUT_USERS_SUCCESS";
export const ADMIN_USERS_SUCCESS = "ADMIN_USERS_SUCCESS";

export const REGISTER_USERS_REQUEST = "REGISTER_USERS_REQUEST";
export const REGISTER_USERS_SUCCESS = "REGISTER_USERS_SUCCESS";
export const REGISTER_USERS_FAILURE = "REGISTER_USERS_FAILURE";

export const GET_REGISTERED_USERS_REQUEST = "GET_REGISTERED_USERS_REQUEST";
export const GET_REGISTERED_USERS_SUCCESS = "GET_REGISTERED_USERS_SUCCESS";
export const GET_REGISTERED_USERS_FAILURE = "GET_REGISTERED_USERS_FAILURE";

export const UPDATE_REGISTERED_USERS_REQUEST =
  "UPDATE_REGISTERED_USERS_REQUEST";
export const UPDATE_REGISTERED_USERS_SUCCESS =
  "UPDATE_REGISTERED_USERS_SUCCESS";
export const UPDATE_REGISTERED_USERS_FAILURE =
  "UPDATE_REGISTERED_USERS_FAILURE";
